Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hotel_Reservation_System.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/Room_UsageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hotel_Reservation_System.Models;

namespace Hotel_Reservation_System.Controllers
{
    [Authorize]
    public class Room_UsageController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public async Task<ActionResult> Index()
        {
            return View(await db.Room_Usage.ToListAsync());
        }

        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room_Usage room_Usage = await db.Room_Usage.FindAsync(id);
            if (room_Usage == null)
            {
                return HttpNotFound();
            }
            return View(room_Usage);
        }

        public ActionResult Create()
        {
            return View(new Room_Usage());
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Room_Id,Guest_Id,Hours,Checkin")] Room_Usage room_Usage)
        {
            if (room_Usage != null)
            {
                room_Usage.Date = DateTime.Now;
            }
            if (ModelState.IsValid)
            {
                List<Room_Usage> usages = db.Room_Usage.ToList().Where(x => x.Room_Id == room_Usage.Room_Id).ToList();
                foreach (var item in usages)
                {
                    if ((item.Checkin >= room_Usage.Checkin && item.Checkin <= room_Usage.CheckOut) ||
                        item.Checkin.AddHours(room_Usage.Hours) >= room_Usage.Checkin)
                    {
                        ModelState.AddModelError("", "Room is not Availble!");
                        return View(room_Usage);
                    }
                }


                db.Room_Usage.Add(room_Usage);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(room_Usage);
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room_Usage room_Usage = await db.Room_Usage.FindAsync(id);
            if (room_Usage == null)
            {
                return HttpNotFound();
            }
            return View(room_Usage);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Room_Id,Guest_Id,Isactive,Date")] Room_Usage room_Usage)
        {
            if (ModelState.IsValid)
            {
                db.Entry(room_Usage).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(room_Usage);
        }

        
        public async Task<JsonResult> Rooms(string RType)
        {
            if (!string.IsNullOrEmpty(RType))
            {
                List<Room> rooms = await db.Rooms.ToListAsync();
                rooms = rooms.ToList().Where(x => x.RType.Trim().ToLower() == 
                            RType.Trim().ToLower()).ToList();
                return Json(new {Rooms = rooms });
            }
            return Json(new {Rooms = new List<Room>() });
        }

        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room_Usage room_Usage = await db.Room_Usage.FindAsync(id);
            if (room_Usage == null)
            {
                return HttpNotFound();
            }
            return View(room_Usage);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Room_Usage room_Usage = await db.Room_Usage.FindAsync(id);
            db.Room_Usage.Remove(room_Usage);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
@*<h3>@ViewBag.Message</h3>*@

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Blue Lagoone</title>

    <link rel="stylesheet" href="~/fonts/main.css">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;700&display=swap" rel="stylesheet">
</head>
<body>



    <main>

        <section class="hero hero-sm" style="background-image: url('../../Images/765715.jpg')">
        </section>

        <section class="section-padding">
            <div class="container">
                <div class="split-section">
                    <div class="split-section__text">
                        <h2>ABOUT</h2>
                        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque doloremque ducimus error excepturi, fugit ipsa iure laudantium magni modi nobis officia placeat possimus quod reprehenderit, similique, sit ullam voluptate voluptates.</p>
                    </div>
                    <div class="split-section__image">
                        <img src="~/Images/Best-Maritim.jpg" alt="#" class="img-shadow img-rounded">
                    </div>
                </div>
            </div>
        </section>




    </main>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="footer-row">
                <ul class="footer-social">
                    <li>
                        <a href="#">
                            <img src="~/Images/icons/facebook.svg" alt="Facebook">
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img src="~/Images/icons/instagram.svg" alt="Instagram">
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img src="~/Images/icons/twitter.svg" alt="Youtube">
                        </a>
                    </li>

                </ul>
            </div>
        </div>
    </footer>

</body>
</html>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>

<address>
    <br />
    <abbr title="Phone">Phone:</abbr>
    +38000000000000
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>HOME</title>

    <link rel="stylesheet" href="~/fonts/main.css">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;700&display=swap" rel="stylesheet">
</head>
<body>
    <section class="hero" style="background-image:url('/Images/icons/so.jpg')">
        <div class="container">
            <h1>Welcome to the Blue Lagoone</h1>
            <p class="lead">Just your relaxion area</p>
        </div>
    </section>
    </body>
<section class="section-padding section-grey">
    <div class="container">
        <div class="split-section">
            <div class="split-section__text">
                <h2>  WHAT IS BLUE LAGOONE?</h2>
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque doloremque ducimus error excepturi, fugit ipsa iure laudantium magni modi nobis officia placeat possimus quod reprehenderit, similique, sit ullam voluptate voluptates.</p>

            </div>
            <div class="split-section__image">
                <section>
                    <video class="center-block" style="max-height:20em" controls loop>
                        <source src="~/Images/videohot.MOV" />
                    </video>
                </section>
            </div>

</section>

    <div class="jumbotron">

        <div id="myCarousel" class="carousel slide" data-ride="carousel" style="max-height:20em">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>

            <div class="carousel-inner" style="max-height:20em">
                <div class="item active">
                    <img src="~/Images/765715.jpg" alt="Chania" class="center-block" style="max-height:20em">
                    <div class="carousel-caption top">
                        <h3>ENJOY THE SCENERY</h3>
                        
                    </div>
                </div>

                <div class="item">
                    <img src="~/Images/icons/room2.jpg" class="center-block" alt="Chicago" style="max-height:20em">
                    <div class="carousel-caption">
                        <h3>RUSH NOW</h3>
                    </div>
                </div>

                <div class="item">
                    <img src="~/Images/Best-Maritim.jpg" class="center-block" alt="New York" style="max-height:20em">
                    <div class="carousel-caption">
                        <h3>RELAX</h3>
                       
                    </div>
                </div>
            </div>

            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 fa-border"
             style="background-color:lightgray; border-width:1em">
            <h2>Getting started</h2>
            <p>
                Create Account in a few simple steps and become eligible to book the best rooms.
            </p>
            <p>@Html.ActionLink("Get Started", "Register", "Account")</p><br />
        </div>
        <div class="col-md-4 fa-border"
             style="background-color:lightblue; border-width:1em">
            <h2>Book Available Rooms</h2>
            <p>Only available rooms can be booked. Click to secure a room for your self and experience the best of luxuries.</p>
            <p>@Html.ActionLink("Am Interested!", "Create", "Room_Usage")</p><br />
        </div>
        <div class="col-md-4 fa-border"
             style="background-color:lightgray; border-width:1em">
            <h2>Booking History</h2>
            <p>View your history and explore your past lodgings. We have an advance search with which you can query your history with us.</p>
            <p>@Html.ActionLink("Am Interested!", "Index", "Room_Usage")</p>
        </div>
    </div>
</html>